
spring.datasource.url = jdbc:postgresql://localhost:5432/employeedbc71
spring.datasource.username =postgres
spring.datasource.password = @kaviarasan@79@
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.properties.hibernate.dialect = 
spring.jpa.hibernate.ddl-auto = update
server.port=8083